### ISSUE TITLE
Unclear update function return value

### ISSUE THREAD

**Issue by nonrecursive** [kristapsdz/openradtool#8]
Maybe I am just missing something, but I figured I would ask to be on the safe side: Next to the function prototype for `db_update` functions, `ort` generates documentation as follows (header.c:265):
```
	print_commentt(0, COMMENT_C_FRAG_CLOSE,
		"Returns zero on failure, non-zero on "
		"constraint errors.");
```

This leaves me wondering: What is the return value if the update is successful?

Looking at the generated code for the update functions did not help clarify things either as it appears to work exactly as documented: `return(KSQL_CONSTRAINT != c);` Maybe there should be a check for `KSQL_DONE`?

**Comment by kristapsdz** [comment]
Because the database (opened in `db_open`) uses the ksql defaults that will error out and quit on failure, the `ksql_stmt_cstep` function will only return `KSQL_CONSTRAINT` or `KSQL_DONE`.

**Comment by kristapsdz** [comment]
This is documented in `db_open` in the header file, but perhaps it's not clear without knowing about ksql, which I don't want to assume.  If you can think of better documentation, let me know!

**Comment by nonrecursive** [comment]
Ah, thanks a lot for the clarification.

In terms of improving the documentation: I'd say it's the first half ("returns zero on failure") that's the most confusing to me. If I understood you correctly, the function only ever returns zero on success, so perhaps it should be "returns zero on success"?

**Comment by kristapsdz** [comment]
Ok, so in practise, I've been using this to say "zero on failure *including constraint violation*" and non-zero on success.  I'm changing it to be zero on constraint violation, <0 on error, >1 on success.  This is backwards compatible in the general case because db_open() ensures that actual errors will cause the system to abort instead of returning failure.  Thank you for the message!  I'll have a fix out in a few.
